export const GET_MOVIES = "GET_MOVIES";
export const DELTE_MOVIES ="DELTE_MOVIES"
export const ADD_MOVIE ="ADD_MOVIE"
export const SINGLE_MOVIES_DATA = "SINGLE_MOVIES_DATA"
export const UPDATE_MOVIE= "UPDATE_MOVIE"
export const REMOVE_SELECTED_MOVIES = "REMOVE_SELECTED_MOVIES"